### ISSUE TITLE
JS-DOC : @return tag always mandatory 

### ISSUE THREAD

**Issue by remigrange** [KleeGroup/eslint-config-focus#1]
The @return tag is always mandatry even on "void" method

**Comment by Bernardstanislas** [comment]
Raised by `require-jsdoc`, need to investigate

**Comment by Bernardstanislas** [comment]
![](http://media1.giphy.com/media/szRuBQwXkSsXm/giphy.gif)

**Comment by Bernardstanislas** [comment]
Solved https://github.com/KleeGroup/eslint-config-focus/commit/1b9fca1f6bb78fea9f648909e9918ae84cf4b937
